matrix:
  include:
    - language: go
      go: "1.11.x"
      before_script:
        - cd go
      script:
        - go test ./topics/cards


    - language: python
      python: 2.7
      before_script:
        - cd python
      script:
        - python -m unittest discover -s ./tests  -p '*_test.py'

